// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCzayiBv6ngizIXnvbXx6tdVwva94tXNQ',
    appId: '1:574595925159:web:8e52a6606e08c16802c782',
    messagingSenderId: '574595925159',
    projectId: 'car-control-de6a4',
    authDomain: 'car-control-de6a4.firebaseapp.com',
    storageBucket: 'car-control-de6a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zsvNyhU_gwLUkhZePlAmeqbBVDQM-yw',
    appId: '1:574595925159:android:cf4e2790a8f5965e02c782',
    messagingSenderId: '574595925159',
    projectId: 'car-control-de6a4',
    storageBucket: 'car-control-de6a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW4y0hYFTQGPfMzK_4RGUHdCIV9SrD5VM',
    appId: '1:574595925159:ios:d0d188d592faa47d02c782',
    messagingSenderId: '574595925159',
    projectId: 'car-control-de6a4',
    storageBucket: 'car-control-de6a4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW4y0hYFTQGPfMzK_4RGUHdCIV9SrD5VM',
    appId: '1:574595925159:ios:d0d188d592faa47d02c782',
    messagingSenderId: '574595925159',
    projectId: 'car-control-de6a4',
    storageBucket: 'car-control-de6a4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCzayiBv6ngizIXnvbXx6tdVwva94tXNQ',
    appId: '1:574595925159:web:74ff5068afa8301302c782',
    messagingSenderId: '574595925159',
    projectId: 'car-control-de6a4',
    authDomain: 'car-control-de6a4.firebaseapp.com',
    storageBucket: 'car-control-de6a4.firebasestorage.app',
  );
}
